### ISSUE TITLE
`ClassNotFoundException` when using CDC Source

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/streaming-integrator#11]
**Description:**
Following error observed when using CDC source(`siddhi-io-cdc_2.0.2`)  on `Streaming Integrator 1.0.0-snapshot`.

```
[2019-07-24 19:58:18,198] ERROR {io.siddhi.core.stream.input.source.Source} - Error on 'CDCListenForUpdates'. Connection to the database lost. Error while connecting at Source 'cdc' at 'UpdateSweetProductionStream'. Will retry in '5 sec'. io.siddhi.core.exception.ConnectionUnavailableException: Connection to the database lost.
	at io.siddhi.extension.io.cdc.source.CDCSource.lambda$connect$1(CDCSource.java:408)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:892)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.debezium.connector.mysql.MySqlConnectorConfig
	at io.debezium.connector.mysql.MySqlConnectorTask.getAllConfigurationFields(MySqlConnectorTask.java:446)
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:38)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:791)
	... 3 more

[2019-07-24 19:58:18,199] ERROR {io.siddhi.core.stream.input.source.Source} - Error on 'CDCListenForDeletes'. Connection to the database lost. Error while connecting at Source 'cdc' at 'DeleteSweetProductionStream'. Will retry in '5 sec'. io.siddhi.core.exception.ConnectionUnavailableException: Connection to the database lost.
	at io.siddhi.extension.io.cdc.source.CDCSource.lambda$connect$1(CDCSource.java:408)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:892)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: com/mysql/cj/jdbc/Driver
	at io.debezium.connector.mysql.MySqlConnectorConfig.<clinit>(MySqlConnectorConfig.java:732)
	at io.debezium.connector.mysql.MySqlConnectorTask.getAllConfigurationFields(MySqlConnectorTask.java:446)
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:38)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:791)
	... 3 more
Caused by: java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver cannot be found by siddhi-io-cdc_2.0.2
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:448)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:361)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:353)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

[2019-07-24 19:58:18,221] ERROR {io.siddhi.core.stream.input.source.Source} - Error on 'CDCListenForInserts'. Connection to the database lost. Error while connecting at Source 'cdc' at 'InsertSweetProductionStream'. Will retry in '5 sec'. io.siddhi.core.exception.ConnectionUnavailableException: Connection to the database lost.
	at io.siddhi.extension.io.cdc.source.CDCSource.lambda$connect$1(CDCSource.java:408)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:892)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.debezium.connector.mysql.MySqlConnectorConfig
	at io.debezium.connector.mysql.MySqlConnectorTask.getAllConfigurationFields(MySqlConnectorTask.java:446)
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:38)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:791)
	... 3 more
```

**Affected Product Version:**
- Streaming Integrator 1.0.0-snapshot
- siddhi-io-cdc_2.0.2

**OS, DB, other environment details and versions:**   
- Mysql connector: mysql-connector-java-5.1.45-bin.jar
- mysql-5.7.27-macos10.14-x86_64
- Mac OS 10.13.1 (17B1003) 

**Steps to reproduce:**
Follow the steps in https://github.com/wso2/docs-ei/blob/master/en/streaming-integrator/docs/examples/cdc-for-mysql.md#capturing-inserts

**Comment by dilini-muthumala** [comment]
`Debezium v0.9.5.final` seems to be dependent on the class `com.mysql.cj.jdbc.Driver` which is found not found in MySQL connector version 5. 

Quoting from [1]

> The name of the class that implements java.sql.Driver in MySQL Connector/J has changed from com.mysql.jdbc.Driver to com.mysql.cj.jdbc.Driver. The old class name has been deprecated.

To overcome this issue, I tried using MySQL connector version 8 but ended up getting below NPE:
```
[2019-07-25 16:35:22,217] ERROR {io.siddhi.core.stream.input.source.Source} - Error on 'CDCListenForDeletes'. Connection to the database lost. Error while connecting at Source 'cdc' at 'DeleteSweetProductionStream'. Will retry in '5 sec'. io.siddhi.core.exception.ConnectionUnavailableException: Connection to the database lost.
at io.siddhi.extension.io.cdc.source.CDCSource.lambda$connect$1(CDCSource.java:408)
at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:887)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException
at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:230)
at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:208)
at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:723)
... 3 more
Caused by: java.lang.NullPointerException
at io.debezium.connector.mysql.Filters.isBuiltInDatabase(Filters.java:33)
at java.util.function.Predicate.lambda$negate$1(Predicate.java:80)
at java.util.function.Predicate.lambda$and$0(Predicate.java:69)
at io.debezium.connector.mysql.MySqlSchema.applyDdl(MySqlSchema.java:338)
at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:414)
... 3 more
```
This is a known bug in debezium which has being fixed in `debezium v0.10.0.Beta3`.

Debezium vv0.10.0 is not released yet. Furthermore I have tried bulding `CDC source` with debezium `v0.9.0.Final` and encountered the same NPE above. 
Therefore decided to downgrade the debezium version to `0.8.3.Final`

[1] https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-api-changes.html
[2] https://issues.jboss.org/browse/DBZ-1409
