### ISSUE TITLE
An error occurs when creating a Siddhi application via REST API

### ISSUE THREAD

**Issue by RukshiW** [wso2/streaming-integrator#116]
**Description:**
The following errors appeared when the curl command to create a new Siddhi application was issued.

```
.exception.SiddhiAppConfigurationException: Exception occurred when retrieving Siddhi App Name 
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorService.getSiddhiAppName(StreamProcessorService.java:288)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorService.validateAndSave(StreamProcessorService.java:254)
	at org.wso2.carbon.streaming.integrator.core.impl.SiddhiAppsApiServiceImpl.siddhiAppsPost(SiddhiAppsApiServiceImpl.java:90)
	at org.wso2.carbon.streaming.integrator.core.impl.SiddhiAppsApiServiceImpl.siddhiAppsPost(SiddhiAppsApiServiceImpl.java:866)
	at org.wso2.carbon.streaming.integrator.core.api.SiddhiAppsApi.siddhiAppsPost(SiddhiAppsApi.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$57(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.siddhi.query.compiler.exception.SiddhiParserException: Error between @ Line: 1. Position: 0 and @ Line: 1. Position: 0. Syntax error in SiddhiQL, mismatched input '<EOF>' expecting {'@', DEFINE, UNEXPECTED_CHAR}.
	at io.siddhi.query.compiler.internal.SiddhiErrorListener.syntaxError(SiddhiErrorListener.java:36)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
	at io.siddhi.query.compiler.SiddhiQLParser.siddhi_app(SiddhiQLParser.java:474)
	at io.siddhi.query.compiler.SiddhiQLParser.parse(SiddhiQLParser.java:178)
	at io.siddhi.query.compiler.SiddhiCompiler.parse(SiddhiCompiler.java:74)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorService.getSiddhiAppName(StreamProcessorService.java:275)
	... 15 more
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Tested this on the Streaming Integrator 101 M1 pack

**Steps to reproduce:**

The following were the steps carried out:

1. Save the following Siddhi Application in a file named "SweetTotalApp.siddhi" in Documents/SiddhiApplications folder.

```
@App:name('SweetTotalApp')

 
define stream SweetProductionStream (name string, amount long);
 
@sink(type='log', prefix='Sweet Totals:')
define stream SweetTotalStream(name string, totalProduction long);
 
@info(name='SweetTotalQuery')
from SweetProductionStream
select name, sum(amount) as totalProduction
group by name
insert into SweetTotalStream;
```

2. Started SI and got the following logs.

```
[2020-05-15 12:01:29,758]  INFO {org.wso2.carbon.streaming.integrator.statistics.api.StatisticsApi} - org.wso2.carbon.streaming.integrator.statistics.api.StatisticsApi service component has  started.
[2020-05-15 12:01:29,762]  INFO {org.wso2.carbon.streaming.integrator.statistics.internal.service.OperatingSystemMetricsServiceComponent} - OperatingSystemMetricsService Component activated
[2020-05-15 12:01:29,828]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiverServiceComponent} - org.wso2.carbon.databridge.receiver.binary.internal.Service Component is activated
[2020-05-15 12:01:29,839]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} - Started Binary SSL Transport on port : 9711
[2020-05-15 12:01:29,841]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} - Started Binary TCP Transport on port : 9611
[2020-05-15 12:01:29,844]  INFO {org.wso2.carbon.databridge.receiver.thrift.internal.ThriftDataReceiverDS} - Service Component is activated
[2020-05-15 12:01:29,868]  INFO {org.wso2.carbon.databridge.receiver.thrift.ThriftDataReceiver} - Thrift Server started at 0.0.0.0
[2020-05-15 12:01:29,890]  INFO {org.wso2.carbon.databridge.receiver.thrift.ThriftDataReceiver} - Thrift SSL port : 7711
[2020-05-15 12:01:29,894]  INFO {org.wso2.carbon.databridge.receiver.thrift.ThriftDataReceiver} - Thrift port : 7611
[2020-05-15 12:01:30,093]  INFO {org.wso2.carbon.siddhi.extensions.installer.core.internal.StartupComponent} - Siddhi Extensions Installer Core Startup Listener Service Component is Activated.
[2020-05-15 12:01:30,114]  INFO {org.wso2.msf4j.internal.MicroservicesServerSC} - All microservices are available
[2020-05-15 12:01:30,117]  INFO {org.wso2.transport.http.netty.contractimpl.listener.ServerConnectorBootstrap$HttpServerConnector} - HTTP(S) Interface starting on host 0.0.0.0 and port 9090
[2020-05-15 12:01:30,118]  INFO {org.wso2.transport.http.netty.contractimpl.listener.ServerConnectorBootstrap$HttpServerConnector} - HTTP(S) Interface starting on host 0.0.0.0 and port 9443
[2020-05-15 12:01:30,588]  INFO {org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorService} - Siddhi App TestSiddhiApp deployed successfully
[2020-05-15 12:01:30,594]  INFO {org.wso2.carbon.kernel.internal.CarbonStartupHandler} - WSO2 Streaming Integrator started in 14.635 sec
```

3. Navigated to **Documents/SiddhiApplications** folder in the terminal.

4. Issued the following CURL command.

```
curl -X POST "https://localhost:9443/siddhi-apps" -H "accept: application/json" -H "Content-Type: text/plain" -d @SweetTotalApp.siddhi -u admin:admin -k
```

**Comment by dnwick** [comment]
This can be closed
