### ISSUE TITLE
Could not publish HTTP events to an OAuth-protected endpoint in SI-1.0.0

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/streaming-integrator#145]
**Description:**
I have followed the documtation[1] to publish HTTP events to an OAuth-protected endpoint in SI-1.0.0.
But it ended up with the below error when trying to used the generated token to access the OAuth protected BE.

```
[2020-08-18 12:09:26,612] ERROR {io.siddhi.core.stream.StreamJunction} - Error in 'FromFileToOmnixApplication' after consuming events from Stream 'HTTPOmnixOutputStream', null. Hence, dropping event 'StreamEvent{ timestamp=1597732766611, beforeWindowData=null, onAfterWindowData=null, outputData=[,,,,,,,,,F5 - Non-Credible,,], type=CURRENT, next=null}' java.lang.NullPointerException
	at io.siddhi.extension.io.http.sink.HttpSink.setAccessToken(HttpSink.java:772)
	at io.siddhi.extension.io.http.sink.HttpSink.sendOauthRequest(HttpSink.java:624)
	at io.siddhi.extension.io.http.sink.HttpSink.publish(HttpSink.java:614)
	at io.siddhi.core.stream.output.sink.Sink.publish(Sink.java:182)
	at io.siddhi.extension.map.json.sinkmapper.JsonSinkMapper.mapAndSend(JsonSinkMapper.java:209)
	at io.siddhi.core.stream.output.sink.SinkMapper.mapAndSend(SinkMapper.java:180)
	at io.siddhi.core.stream.output.sink.SinkCallback.receive(SinkCallback.java:55)
	at io.siddhi.core.stream.output.StreamCallback.receive(StreamCallback.java:100)
	at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:176)
	at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:465)
	at io.siddhi.core.query.output.callback.InsertIntoStreamCallback.send(InsertIntoStreamCallback.java:56)
	at io.siddhi.core.query.output.ratelimit.OutputRateLimiter.sendToCallBacks(OutputRateLimiter.java:104)
	at io.siddhi.core.query.output.ratelimit.PassThroughOutputRateLimiter.process(PassThroughOutputRateLimiter.java:44)
	at io.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:97)
	at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:183)
	at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:90)
	at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:146)
	at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:224)
	at io.siddhi.core.stream.StreamJunction.access$000(StreamJunction.java:61)
	at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:483)
	at io.siddhi.core.stream.input.InputDistributor.send(InputDistributor.java:39)
	at io.siddhi.core.stream.input.InputEntryValve.send(InputEntryValve.java:55)
	at io.siddhi.core.stream.input.InputHandler.send(InputHandler.java:91)
	at io.siddhi.core.stream.input.source.PassThroughSourceHandler.sendEvents(PassThroughSourceHandler.java:40)
	at io.siddhi.core.stream.input.source.InputEventHandler.sendEvents(InputEventHandler.java:111)
	at io.siddhi.extension.map.csv.sourcemapper.CSVSourceMapper.mapAndProcess(CSVSourceMapper.java:226)
	at io.siddhi.core.stream.input.source.SourceMapper.onEvent(SourceMapper.java:152)
	at io.siddhi.core.stream.input.source.SourceMapper.onEvent(SourceMapper.java:118)
	at io.siddhi.extension.io.file.processors.FileProcessor.receive(FileProcessor.java:74)
	at org.wso2.transport.file.connector.sender.VFSClientConnector.send(VFSClientConnector.java:205)
	at io.siddhi.extension.io.file.listeners.FileSystemListener.onMessage(FileSystemListener.java:92)
	at org.wso2.transport.remotefilesystem.server.RemoteFileSystemConsumer.consume(RemoteFileSystemConsumer.java:164)
	at org.wso2.transport.remotefilesystem.server.connector.contractimpl.RemoteFileSystemServerConnectorImpl.poll(RemoteFileSystemServerConnectorImpl.java:56)
	at io.siddhi.extension.io.file.FileSourcePoller.run(FileSourcePoller.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

[1] - https://ei.docs.wso2.com/en/latest/streaming-integrator/samples/PublishHttpOAuthRequest/

**Affected Product Version:**
SI 1.0.0

**Comment by dilini-muthumala** [comment]
Closing this as this is a duplicate of https://github.com/wso2/streaming-integrator/issues/144
