### ISSUE TITLE
SIDDHI_ERROR_STORE_TABLE cause column too short for some errors

### ISSUE THREAD

**Issue by niruhan** [wso2/streaming-integrator#150]
**Steps to reproduce:**

Deploy following siddhi app in server
```
@App:name("Store-rdbms")

@App:description('Receive events via simulator and persist the received data in the store.')

@sink(type='log')
define stream logStream(name string, amount double);

@Store(type="rdbms",
       jdbc.url="jdbc:mysql://localhost:3307/production?useSSL=false",
       username="root",
       password="root",
       on.error="store",
       jdbc.driver.name="com.mysql.jdbc.Driver")
@index("amount")
define table SweetProductionTable (name string, amount double);

@Source(type = 'http',
        receiver.url='http://localhost:8006/productionStream',
        basic.auth.enabled='false',
        @map(type='json'))
define stream insertSweetProductionStream (name string, amount double);

/* Inserting event into the mysql database */
@info(name='query1')
from insertSweetProductionStream
insert into SweetProductionTable;

from insertSweetProductionStream
insert into logStream;
```

Send the following request to `http://localhost:8006/productionStream`
```
{
    "event": {
        "nam": "Cake",
        "amount": 20.12
    }
}
```

You will observe the following logs

```
[2020-09-04 12:31:39,513] ERROR {io.siddhi.extension.map.json.sourcemapper.JsonSourceMapper} - Stream "insertSweetProductionStream" does not have an attribute named "nam", but the received event {
    "event": {
        "nam": "Cake",
        "amount": 20.12
    }
} does. Hence dropping the message. Check whether the json string is in a correct format for default mapping.
[2020-09-04 12:31:39,519] ERROR {io.siddhi.core.stream.input.source.SourceMapper} - Error while processing '{
    "event": {
        "nam": "Cake",
        "amount": 20.12
    }
}', for the input Mapping 'json' for the stream 'insertSweetProductionStream'. io.siddhi.core.exception.MappingFailedException
        at io.siddhi.extension.map.json.sourcemapper.JsonSourceMapper.mapAndProcess(JsonSourceMapper.java:242)
        at io.siddhi.core.stream.input.source.SourceMapper.onEvent(SourceMapper.java:200)
        at io.siddhi.core.stream.input.source.SourceMapper.onEvent(SourceMapper.java:144)
        at io.siddhi.extension.io.http.source.HttpWorkerThread.run(HttpWorkerThread.java:62)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

[2020-09-04 12:31:39,538] ERROR {org.wso2.carbon.streaming.integrator.core.siddhi.error.handler.DBErrorStore} - Error while saving to SIDDHI_ERROR_STORE_DB com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'cause' at row 1
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at org.wso2.carbon.streaming.integrator.core.siddhi.error.handler.DBErrorStore.saveEntry(DBErrorStore.java:206)
        at io.siddhi.core.util.error.handler.store.ErrorStore.lambda$getEventHandler$0(ErrorStore.java:90)
        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
        at java.lang.Thread.run(Thread.java:748)
```

**Affected Product Version:**
wso2si-1.1.0

**OS, DB, other environment details and versions:**
MySQL 5.6, MacOS Catalina 10.15.6, JDK 1.8.0_201

**Comment by senthuran16** [comment]
The length of `cause` column is set from [here](https://github.com/wso2/carbon-analytics/blob/master/components/org.wso2.carbon.streaming.integrator.core/src/main/resources/error-store-queries.yaml#L43). 
```
CREATE_TABLE: CREATE TABLE {{TABLE_NAME}} (id INT NOT NULL AUTO_INCREMENT, timestamp BIGINT, siddhiAppName VARCHAR (100), streamName VARCHAR(100), event LONGBLOB, cause VARCHAR(255), stackTrace LONGBLOB, originalPayload LONGBLOB, errorOccurrence VARCHAR(50), eventType VARCHAR(50), errorType VARCHAR(50), PRIMARY KEY (id))
```
Let's change its length to `1000`.
```... , cause VARCHAR(1000), ...```

(Note that this has to be done `CREATE_TABLE` mappings of all the listed database types)

**Comment by niruhan** [comment]
I confirm that setting the "cause" column to size 1000 solves this issue.

**Comment by senthuran16** [comment]
Let's also trim the `cause` to 1000 characters before saving it, so that in case if it exceeds 1000 characters, the same exception won't be thrown.

It can be done [here](https://github.com/wso2/carbon-analytics/blob/master/components/org.wso2.carbon.streaming.integrator.core/src/main/java/org/wso2/carbon/streaming/integrator/core/siddhi/error/handler/DBErrorStore.java#L174).

**Comment by niruhan** [comment]
Fixed in https://github.com/wso2/carbon-analytics/pull/1900
