### ISSUE TITLE
SFTP support for file i/o

### ISSUE THREAD

**Issue by niruhan** [wso2/streaming-integrator#163]
**Description:**
siddhi-io-file examples are shown using FTP.  When trying out the file transfer using SFTP protocol using the following siddhi app

```
@App:name('SFTPFileTransfer')
@App:description('Transferring files through SFTP')

@source(type = 'http', receiver.url = "http://localhost:8005/inputpathStream", basic.auth.enabled = "false",
	@map(type = 'json',
		@attributes(sourcePath = "$.event.value1", targetPath = "$.event.value2")))
define stream InputPathStream (sourcePath string, targetPath string);

@info(name = 'query1')
from InputPathStream#file:move(sourcePath, "sftp://<path>") 
select * 
insert into OutputStream;
```

we get the following error

```
io.siddhi.core.exception.SiddhiAppRuntimeException: Exception occurred when resolving path for: sftp://<file_path> at io.siddhi.extension.util.Utils.getFileObject(Utils.java:84) at io.siddhi.extension.execution.file.FileMoveExtension.moveFileToDestination(FileMoveExtension.java:240) at io.siddhi.extension.execution.file.FileMoveExtension.process(FileMoveExtension.java:183) at io.siddhi.core.query.processor.stream.function.StreamFunctionProcessor.processEventChunk(StreamFunctionProcessor.java:65) at io.siddhi.core.query.processor.stream.AbstractStreamProcessor.process(AbstractStreamProcessor.java:132) at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:182) at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:89) at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:127) at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:202) at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:505) at io.siddhi.core.stream.input.InputDistributor.send(InputDistributor.java:34) at io.siddhi.core.stream.input.InputEntryValve.send(InputEntryValve.java:45) at io.siddhi.core.stream.input.InputHandler.send(InputHandler.java:78) at io.siddhi.core.stream.input.source.PassThroughSourceHandler.sendEvent(PassThroughSourceHandler.java:35) at io.siddhi.core.stream.input.source.InputEventHandler.sendEvent(InputEventHandler.java:84) at io.siddhi.extension.map.json.sourcemapper.JsonSourceMapper.mapAndProcess(JsonSourceMapper.java:238) at io.siddhi.core.stream.input.source.SourceMapper.onEvent(SourceMapper.java:200) at io.siddhi.core.stream.input.source.SourceMapper.onEvent(SourceMapper.java:144) at io.siddhi.extension.io.http.source.HttpWorkerThread.run(HttpWorkerThread.java:62) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) at java.base/java.lang.Thread.run(Thread.java:832) Caused by: org.apache.commons.vfs2.FileSystemException: Badly formed URI "sftp://<file_path>". at org.apache.commons.vfs2.provider.url.UrlFileProvider.findFile(UrlFileProvider.java:75) at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:793) at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:658) at io.siddhi.extension.util.Utils.getFileObject(Utils.java:82) ... 21 more Caused by: java.net.MalformedURLException: unknown protocol: sftp at java.base/java.net.URL.(URL.java:679) at java.base/java.net.URL.(URL.java:568) at java.base/java.net.URL.(URL.java:515) at org.apache.commons.vfs2.provider.url.UrlFileProvider.findFile(UrlFileProvider.java:60) ... 24 more
```

**Affected Product Version:**
1.1.0

**Comment by niruhan** [comment]
Fixed in https://github.com/siddhi-io/siddhi-io-file/pull/111 & https://github.com/wso2/transport-file/pull/24
