### ISSUE TITLE
Siddhi app, with multiple define stream statements, fails to deploy through REST API

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/streaming-integrator#18]
**Description:**
Following Siddhi app gets deployed successfully when I place it in `<SI_home>/wso2/server/deployment/siddhi-files`

but it fails to get deployed when I deploy via Siddhi Query API.

### Siddhi app:
```
@App:name("Store-rdbms2")

@App:description('Receive events via simulator and persist the received data in the store.')

define stream insertSweetProductionStream (name string, amount double);

define stream updateSweetProductionStream (name string, amount double);

@sink(type='log')
define stream searchSweetProductionStream (name string);

@sink(type='log')
define stream logStream(name string, amount double);

@Store(type="rdbms",
       jdbc.url="jdbc:mysql://localhost:3306/production?useSSL=false",
       username="wso2",
       password="wso2" ,
       jdbc.driver.name="com.mysql.jdbc.Driver")
define table SweetProductionTable (name string, amount double);

from insertSweetProductionStream
insert into SweetProductionTable;

from updateSweetProductionStream
update SweetProductionTable
on SweetProductionTable.name == name ;
```

### Error:
```
osgi> [2019-08-16 15:53:52,381] ERROR {org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorService} - Exception occurred when validating Siddhi App org.wso2.carbon.streaming.integrator.core.internal.exception.SiddhiAppConfigurationException: Exception occurred when retrieving Siddhi App Name
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorService.getSiddhiAppName(StreamProcessorService.java:288)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorService.validateAndSave(StreamProcessorService.java:254)
	at org.wso2.carbon.streaming.integrator.core.impl.SiddhiAppsApiServiceImpl.siddhiAppsPost(SiddhiAppsApiServiceImpl.java:90)
	at org.wso2.carbon.streaming.integrator.core.impl.SiddhiAppsApiServiceImpl.siddhiAppsPost(SiddhiAppsApiServiceImpl.java:866)
	at org.wso2.carbon.streaming.integrator.core.api.SiddhiAppsApi.siddhiAppsPost(SiddhiAppsApi.java:81)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$57(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.siddhi.query.compiler.exception.SiddhiParserException: Error between @ Line: 1. Position: 0 and @ Line: 1. Position: 688. Syntax error in SiddhiQL, no viable alternative at input 'into'.
	at io.siddhi.query.compiler.internal.SiddhiErrorListener.syntaxError(SiddhiErrorListener.java:36)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:566)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:308)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:145)
	at io.siddhi.query.compiler.SiddhiQLParser.query_output(SiddhiQLParser.java:6028)
	at io.siddhi.query.compiler.SiddhiQLParser.query(SiddhiQLParser.java:2735)
	at io.siddhi.query.compiler.SiddhiQLParser.execution_element(SiddhiQLParser.java:510)
	at io.siddhi.query.compiler.SiddhiQLParser.siddhi_app(SiddhiQLParser.java:444)
	at io.siddhi.query.compiler.SiddhiQLParser.parse(SiddhiQLParser.java:178)
	at io.siddhi.query.compiler.SiddhiCompiler.parse(SiddhiCompiler.java:72)
	at org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorService.getSiddhiAppName(StreamProcessorService.java:275)
	... 14 more
```

**Observation**
What I have noted is, if I remove following lines from the app, it works:
```
define stream updateSweetProductionStream (name string, amount double);
```
```
from updateSweetProductionStream
update SweetProductionTable
on SweetProductionTable.name == name ;
```
I'm guessing that when the app has multiple `define stream` definitions, this happens.

**Affected Product Version:**
wso2si-1.0.0-SNAPSHOT

**Steps to reproduce:**
Start SI server and deploy above siddhi app.

**Comment by niruhan** [comment]
The issue is with the following command;

`curl -X POST "https://localhost:9443/siddhi-apps" -H "accept: application/json" -H "Content-Type: text/plain" --data @Store-rdbms2.siddhi -u admin:admin -k `

When using `--data` tag the curl drops newlines in the siddhi file. Using `--data-binary` tag instead of `--data` will preserve newlines and hence solve the issue
