### ISSUE TITLE
[Async API] FileNotFoundException occurs intermittently when updating the Async api siddhi app 

### ISSUE THREAD

**Issue by AnuGayan** [wso2/streaming-integrator#223]
**Description:**
The following error occurred intermittently when updating an existing async API related siddhi app
```
ERROR {org.wso2.carbon.streaming.integrator.core.internal.asyncapi.AsyncAPIDeployer} - Exception occurred when generating md5 for async api: TestApp-1.0.0 java.io.FileNotFoundException: /Users/anushaj/wso2/Projects/ReleaseTest/wso2si-4.0.0-SNAPSHOT/wso2/server/deployment/.service-definitions/TestApp-1.0.0/TestApp-1.0.0/definition.yaml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.wso2.carbon.streaming.integrator.core.internal.asyncapi.util.Md5HashGenerator.getFileChecksum(Md5HashGenerator.java:89)
	at org.wso2.carbon.streaming.integrator.core.internal.asyncapi.util.Md5HashGenerator.calculateHash(Md5HashGenerator.java:76)
	at org.wso2.carbon.streaming.integrator.core.internal.asyncapi.util.Md5HashGenerator.validateInputParams(Md5HashGenerator.java:61)
	at org.wso2.carbon.streaming.integrator.core.internal.asyncapi.util.Md5HashGenerator.generateHash(Md5HashGenerator.java:48)
	at org.wso2.carbon.streaming.integrator.core.internal.asyncapi.AsyncAPIDeployer.isMD5Equal(AsyncAPIDeployer.java:163)
	at org.wso2.carbon.streaming.integrator.core.internal.asyncapi.AsyncAPIDeployer.run(AsyncAPIDeployer.java:84)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Exception in thread "pool-9-thread-2" io.siddhi.core.exception.SiddhiAppRuntimeException: IOException occurred when archiving  /Users/anushaj/wso2/Projects/ReleaseTest/wso2si-4.0.0-SNAPSHOT/wso2/server/deployment/.service-definitions/TestApp-1.0.0
	at org.wso2.carbon.streaming.integrator.core.internal.asyncapi.AsyncAPIDeployer.zipFiles(AsyncAPIDeployer.java:112)
	at org.wso2.carbon.streaming.integrator.core.internal.asyncapi.AsyncAPIDeployer.run(AsyncAPIDeployer.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /Users/anushaj/wso2/Projects/ReleaseTest/wso2si-4.0.0-SNAPSHOT/wso2/server/deployment/.service-definitions/TestApp-1.0.0/TestApp-1.0.0.zip (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at org.wso2.carbon.streaming.integrator.core.internal.asyncapi.util.Utils.zip(Utils.java:56)
	at org.wso2.carbon.streaming.integrator.core.internal.asyncapi.AsyncAPIDeployer.zipFiles(AsyncAPIDeployer.java:110)
	... 4 more
```

**Affected Product Version:**
Streaming Integrator 4.0.0-beta

**Comment by dnwick** [comment]
fixed with https://github.com/wso2/carbon-analytics/pull/1946
